services:
  app:
    build:
      context: .
    environment:
      - Logging__LogLevel__Microsoft.AspNetCore.DataProtection=Error
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=gruppe6_db;User=root;Password=passord;
      - DOTNET_RUNNING_IN_DOCKER=true
    volumes:
      - gruppe_6_kartverket_app_data:/app/data
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:12
    environment:
      - MARIADB_DATABASE=gruppe6_kartverket
      - MARIADB_ROOT_PASSWORD=passord
    volumes:
      - gruppe_6_kartverket_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb --user=root --password=passord --host=127.0.0.1 --protocol=tcp -e 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s

  dbgate:
    image: dbgate/dbgate:6.7.1
    environment:
      CONNECTIONS: db
      LABEL_db: "MariaDB Database"
      SERVER_db: db
      USER_db: root
      PASSWORD_db: passord
      PORT_db: 3306
      ENGINE_db: mysql@dbgate-plugin-mysql
    volumes:
      - gruppe_6_dbgate:/root/.dbgate
    ports:
      - "3000:3000"
    restart: always

volumes:
  gruppe_6_kartverket_db_data: {}
  gruppe_6_kartverket_app_data: {}
  gruppe_6_dbgate: {}
